name: DSLab Autograding Workflow

'on':
  push:
    branches:
      - main

permissions:
  checks: write
  contents: read
  actions: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run-autograding-tests:
    runs-on: dsg-dslab-k8s-runners
    if: github.actor != 'github-classroom[bot]'

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Test client_01_return_correct_componentId
        id: client_01_return_correct_componentId
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: client_01_return_correct_componentId
          setup-command: ''
          command: mvn test -Dtest=dslab.ClientTest#client_01_return_correct_componentId
          timeout: 1
          max-score: 1

      - name: Test client_02_correct_thread_lifecycle
        id: client_02_correct_thread_lifecycle
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: client_02_correct_thread_lifecycle
          setup-command: ''
          command: mvn test -Dtest=dslab.ClientTest#client_02_correct_thread_lifecycle
          timeout: 1
          max-score: 2

      - name: Test displays_correct_prompt
        id: displays_correct_prompt
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: displays_correct_prompt
          setup-command: ''
          command: mvn test -Dtest=dslab.ClientCLITest#displays_correct_prompt
          timeout: 1
          max-score: 1

      - name: Test empty_newline_command
        id: empty_newline_command
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: empty_newline_command
          setup-command: ''
          command: mvn test -Dtest=dslab.ClientCLITest#empty_newline_command
          timeout: 1
          max-score: 1

      - name: Test unknown_command
        id: unknown_command
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: unknown_command
          setup-command: ''
          command: mvn test -Dtest=dslab.ClientCLITest#unknown_command
          timeout: 1
          max-score: 1

      - name: Test shutdown_basic_command_validation
        id: shutdown_basic_command_validation
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: shutdown_basic_command_validation
          setup-command: ''
          command: mvn test -Dtest=dslab.ClientCLITest#shutdown_basic_command_validation
          timeout: 1
          max-score: 1

      - name: Test shutdown_command_sends_exit
        id: shutdown_command_sends_exit
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: shutdown_command_sends_exit
          setup-command: ''
          command: mvn test -Dtest=dslab.ClientCLITest#shutdown_command_sends_exit
          timeout: 1
          max-score: 1

      - name: Test channel_command
        id: channel_command
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: channel_command
          setup-command: ''
          command: mvn test -Dtest=dslab.ClientCLITest#channel_command
          timeout: 1
          max-score: 4

      - name: Test channel_basic_command_validation
        id: channel_basic_command_validation
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: channel_basic_command_validation
          setup-command: ''
          command: mvn test -Dtest=dslab.ClientCLITest#channel_basic_command_validation
          timeout: 1
          max-score: 2

      - name: Test channel_invalid_config_validation
        id: channel_invalid_config_validation
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: channel_invalid_config_validation
          setup-command: ''
          command: mvn test -Dtest=dslab.ClientCLITest#channel_invalid_config_validation
          timeout: 1
          max-score: 2

      - name: Test channel_error_handling
        id: channel_error_handling
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: channel_error_handling
          setup-command: ''
          command: mvn test -Dtest=dslab.ClientCLITest#channel_error_handling
          timeout: 1
          max-score: 2

      - name: Test subscribe_command
        id: subscribe_command
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: subscribe_command
          setup-command: ''
          command: mvn test -Dtest=dslab.ClientCLITest#subscribe_command
          timeout: 1
          max-score: 5

      - name: Test subscribe_command_without_channel
        id: subscribe_command_without_channel
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: subscribe_command_without_channel
          setup-command: ''
          command: mvn test -Dtest=dslab.ClientCLITest#subscribe_command_without_channel
          timeout: 1
          max-score: 2

      - name: Test subscribe_basic_command_validation
        id: subscribe_basic_command_validation
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: subscribe_basic_command_validation
          setup-command: ''
          command: mvn test -Dtest=dslab.ClientCLITest#subscribe_basic_command_validation
          timeout: 1
          max-score: 2

      - name: Test subscription_correct_callback_and_thread_behaviour
        id: subscription_correct_callback_and_thread_behaviour
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: subscription_correct_callback_and_thread_behaviour
          setup-command: ''
          command: mvn test -Dtest=dslab.ClientCLITest#subscription_correct_callback_and_thread_behaviour
          timeout: 1
          max-score: 4

      - name: Test publish_command
        id: publish_command
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: publish_command
          setup-command: ''
          command: mvn test -Dtest=dslab.ClientCLITest#publish_command
          timeout: 1
          max-score: 5

      - name: Test publish_command_without_channel
        id: publish_command_without_channel
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: publish_command_without_channel
          setup-command: ''
          command: mvn test -Dtest=dslab.ClientCLITest#publish_command_without_channel
          timeout: 1
          max-score: 2

      - name: Test publish_basic_command_validation
        id: publish_basic_command_validation
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: publish_basic_command_validation
          setup-command: ''
          command: mvn test -Dtest=dslab.ClientCLITest#publish_basic_command_validation
          timeout: 1
          max-score: 2

      - name: Autograding Reporter
        uses: classroom-resources/autograding-grading-reporter@v1
        env:
          CLIENT_01_RETURN_CORRECT_COMPONENTID_RESULTS: ${{steps.client_01_return_correct_componentId.outputs.result}}
          CLIENT_02_CORRECT_THREAD_LIFECYCLE_RESULTS: ${{steps.client_02_correct_thread_lifecycle.outputs.result}}
          DISPLAYS_CORRECT_PROMPT_RESULTS: ${{steps.displays_correct_prompt.outputs.result}}
          EMPTY_NEWLINE_COMMAND_RESULTS: ${{steps.empty_newline_command.outputs.result}}
          UNKNOWN_COMMAND_RESULTS: ${{steps.unknown_command.outputs.result}}
          SHUTDOWN_BASIC_COMMAND_VALIDATION_RESULTS: ${{steps.shutdown_basic_command_validation.outputs.result}}
          SHUTDOWN_COMMAND_SENDS_EXIT_RESULTS: ${{steps.shutdown_command_sends_exit.outputs.result}}
          CHANNEL_COMMAND_RESULTS: ${{steps.channel_command.outputs.result}}
          CHANNEL_BASIC_COMMAND_VALIDATION_RESULTS: ${{steps.channel_basic_command_validation.outputs.result}}
          CHANNEL_INVALID_CONFIG_VALIDATION_RESULTS: ${{steps.channel_invalid_config_validation.outputs.result}}
          CHANNEL_ERROR_HANDLING_RESULTS: ${{steps.channel_error_handling.outputs.result}}
          SUBSCRIBE_COMMAND_RESULTS: ${{steps.subscribe_command.outputs.result}}
          SUBSCRIBE_COMMAND_WITHOUT_CHANNEL_RESULTS: ${{steps.subscribe_command_without_channel.outputs.result}}
          SUBSCRIBE_BASIC_COMMAND_VALIDATION_RESULTS: ${{steps.subscribe_basic_command_validation.outputs.result}}
          SUBSCRIPTION_CORRECT_CALLBACK_AND_THREAD_BEHAVIOUR_RESULTS: ${{steps.subscription_correct_callback_and_thread_behaviour.outputs.result}}
          PUBLISH_COMMAND_RESULTS: ${{steps.publish_command.outputs.result}}
          PUBLISH_COMMAND_WITHOUT_CHANNEL_RESULTS: ${{steps.publish_command_without_channel.outputs.result}}
          PUBLISH_BASIC_COMMAND_VALIDATION_RESULTS: ${{steps.publish_basic_command_validation.outputs.result}}
        with:
          runners: client_01_return_correct_componentId,client_02_correct_thread_lifecycle,displays_correct_prompt,empty_newline_command,unknown_command,shutdown_basic_command_validation,shutdown_command_sends_exit,channel_command,channel_basic_command_validation,channel_invalid_config_validation,channel_error_handling,subscribe_command,subscribe_command_without_channel,subscribe_basic_command_validation,subscription_correct_callback_and_thread_behaviour,publish_command,publish_command_without_channel,publish_basic_command_validation
